language: python
matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.6
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - nosetests --with-coverage --cover-erase --cover-package awsanalysis --cover-html -v tests/functional/
  - coveralls

after_success:
  - rm -r cover

